######################################################################
# Automatically generated by qmake (2.01a) Sat Jul 2 05:05:08 2011
######################################################################

TEMPLATE = app
TARGET = browserjet-bin
DEPENDPATH += .
INCLUDEPATH += .
QT += webkit
DESTDIR = ../bin

# Input
HEADERS += browser.h stdinreader.h json.h webpage.h browserjetobject.h
SOURCES += browserjet.cpp browser.cpp stdinreader.cpp json.cpp webpage.cpp browserjetobject.cpp